name: Train
description: Training
inputs:
  - {name: image, description: ''}
  - {name: update_data, description: ''}
  - {name: git_rev, description: ''}
  - {name: config, description: ''}
  - {name: name, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '932360549041.dkr.ecr.us-west-2.amazonaws.com/genie-toolkit-jupyter:headset-overlay-hpe-v0-5'
    command: [
        python3, /workspace/train.py,
        --git_rev, { inputValue: git_rev },
        --update_data, { inputValue: update_data },
        --config, { inputValue: config },
        --name, { inputValue: name },
        --additional_args, { inputValue: additional_args },
    ]
# --tensorboard_dir /shared/tensorboard/${project}/${experiment}/${owner}/${model}
